#server
server:
  port: 8080
  #项目访问名（注意springboot1.5.x及以下版本配置使用）
  #context-path: /study-demo
  servlet:
    #项目访问名（注意springboot2.x及以上版本配置使用）
    context-path: /study-demo
  max-http-header-size: 10240000
  tomcat:
    uri-encoding: UTF-8
    max-threads: 10240000
    max-http-post-size: 10240000    
#profile
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    #限制文件上传大小（注意springboot1.5.x及以配置版本才使用）
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
  #限制文件上传大小（注意springboot2.x及以上版本配置使用）
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  
  mvc:
    servlet:
      load-on-startup: 1 
  # 模板引擎
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    #非严格检查标签元素（注意：thymeleaf模板2.x及以下低版本要改成LEGACYHTML5）
    #mode: LEGACYHTML5
    mode: HTML5
    encoding: utf-8
    #项目访问名（注意springboot1.5.x及以下版本配置使用）
    content-type: text/html
    servlet:
      #（注意springboot2.x及以上版本配置使用）
      content-type: text/html
    # 禁用缓存
    cache: false
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #多个war包在同一tomcat下同时部署时，需不同jmx域
  jmx:
    #是否将管理bean暴露给JMX域，默认true
    #方法一：enabled=false
    enabled: false
    #方法二：default-domain=唯一的名字
    default-domain: study-demo
  #邮箱配置
  mail:
    host: smtp.163.com
    port: 994
    username: xxxx@163.com
    password: xxxx
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          timeout: 30000
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 994
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
              
#Mybatis配置    
mybatis:
  type-aliases-package: com.cnstock
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configLocation: classpath:mybatis-config.xml
  
#异步线程池配置
async-task:
  executor:
     #核心线程数
     corePoolSize: 50
     #最大线程数
     maxPoolSize: 400
     #队列大小
     queueCapacity: 100
     #允许线程的空闲时间(单位：秒)
     keepAliveSeconds: 60
     #线程的名称前缀
     threadNamePrefix: async-service-
